name: build

on: [pull_request, push]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build with PlatformIO
              run: bash ci/build_platformio
