name: build

on: [pull_request, push]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.6'

            - name: Build with PlatformIO
              run: bash build.sh
