name: lint

on: [pull_request, push]

jobs:
    lint:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Lint C source
              run: |
                sudo apt-get -y install clang-format
                bash lint-c.sh

            - name: Lint shell scripts
              run: bash lint-shell.sh
