name: lint

on: [pull_request, push]

jobs:
    lint:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Lint C source
              run: |
                sudo apt-get -y install clang-format
                bash lint-c.sh

            - name: Lint shell scripts
              run: bash lint-shell.sh

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.6'
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Lint Python files
              run: bash lint-python.sh

            - name: Lint YAML files
              run: bash lint-yaml.sh
